### ISSUE TITLE
Amazon pricing data doesn't seem to be working

### ISSUE THREAD

**Issue by Goolyio** [ffeathers/Elektra-Auto-Checkout#2]
Hey,

For me I am now unable to get pricing data from the amazon data api you also use. Requesting the product price data using the accept header

```
application/vnd.com.amazon.api+json; type="collection(product/v2)/v1"; expand="buyingOptions[].price(product.price/v1)"`
```
Results in an error when trying to expand the pricing options with a message saying `"You do not have authorization for the requested resource."`

```json
{
   "resource":{
      "types":[
         "collection(product/v1)/v1",
         "collection(product/v2)/v1",
         "collection(product.mini/v1)/v1"
      ],
      "url":"/api/marketplaces/ATVPDKIKX0DER/products/B09BDG5RP3"
   },
   "type":"collection(product/v2)/v1",
   "entities":[
      {
         "resource":{
            "url":"/api/marketplaces/ATVPDKIKX0DER/products/B09BDG5RP3",
            "types":[
               "product/v2",
               "product.offer-comparison-experience/v1",
               "product.mini/v1",
               "product/v1"
            ]
         },
         "type":"product/v2",
         "entity":{
            "asin":"B09BDG5RP3",
            "buyingOptions":[
               {
                  "price":{
                     "resource":{
                        "url":"/api/marketplaces/ATVPDKIKX0DER/products/B09BDG5RP3/buying-options/0yjXUM2kMWcCfOqbDAGE3qI5hQwZh-jXK4f1IBZ_HYQ%3D/price",
                        "types":[
                           "product.price/v1"
                        ]
                     },
                     "type":"error/v1",
                     "metadata":{
                        "x-amzn-metrics-id":"INTER_RANKED:c0ae1917-6e96-3909-89ae-d48973e76a97",
                        "x-amzn-metrics-id":"MBOS:0bf8dea4-1030-3997-9bc9-73431c69ae7d",
                        "x-api-exp-data":"GLOBAL_STORE_FORT_PLUGIN_OFFER_SUPPRESSION_468651:T1,PRR_UPSELL_BOAPI_INTEGRATION_GSOD_494140:T1,BUYING_OPTION_GLOBAL_STORE_GUARDRAIL_452747:T1,ADBL_HS_MINERVA_LOOM_BUYING_OPTIONS_258906:T1,OFFERSX_BOPIS_CX_ROAR_500067:T1,GLOBAL_STORE_SKIP_FMA_IFD_OVERRIDE_508576:T1,MOD_PRIME_GLOBAL_STORE_SUPPRESSION_481007:T1"
                     },
                     "entity":{
                        "code":"403.1",
                        "details":{
                           "message":"You do not have authorization for the requested resource.",
                           "url":"https://api.amazon.com/shop"
                        },
                        "encryptedInternalInfo":"Z/XkAL9bIxm133wf7FKPpWevX9iWYZAvVGyOTboHMXCYRsNigeslowrGMeJU8+0yuAOwjG5PBDgecAVDLz5H4KQca3/n+V6/xPpf4+1NnSBaYalokWkt1SAGboXkG20r2fPzNPNFqmyD1+TN/aQFRgH2Btd95aaqJeEGGZmcPFereoTPfGGtbpWQV6fF18uaB0MWDwPzFkI6RmMbSkBKeeyj3vbC3JtSj+WR6hJuWG5H3aPjm14KOw00AzyVX9nYDDqrFf5fyjA8so3ghFSJbfEmGHXeyutaCO3XiU45GxI1xjN/SjZFuWgIGVsQwJpsu1ZVoyjWCoB0KIuASz3F2bTvVbmsDR5ysegDG1o8Cks9EFpMWcn1eYbLR1X3lh/Wx/M5M4lvx06N75hyOx4ABrSY5NTL474kolxPI0eNZwZjrZr3Jy3GMmP5SzQYnLUWPdyKvEIDDL+H++/R+yJ0ICF8hiPMc+SbqjoVY1mkzx6eZYshS14NL0KUoBkrD/4yqyUGWLv8jJ0FCdtxj7Lu5xWjCo1yDVxMig9Qa4vlF2yJYUfa5J6InAVtWZAAP5xhRE0crLYZ63Q3n1y0hdTQQ0TB64xjo9rwCdC/e+mB/2M4gXAkkLYWyMUkm8OKJadj",
                        "status":403
                     }
                  },
                  "type":"NEW"
               }
            ]
         }
      }
   ]
}
```

Is this the same for you?

**Comment by lucamancusodev** [comment]
me too.
I receive 403 using US marketplace (ATVPDKIKX0DER) and 404 if I use IT marketplace (APJ6JRA9NG5V4)

**Comment by Johnw7789** [comment]
There have been a few changes made since I published this repo a long time ago. Both a csrf token and slate token are needed and can be found on various product pages (Amazon echo as an example). Beyond that, I can’t offer any time to update the repo.

**Comment by lucamancusodev** [comment]
> There have been a few changes made since I published this repo a long time ago. Both a csrf token and slate token are needed and can be found on various product pages (Amazon echo as an example). Beyond that, I can’t offer any time to update the repo.

Thank you for the hint.
I added `req.Header.Set("x-amzn-encrypted-slate-token", slateToken)`

but I receive 400 using US marketplace (ATVPDKIKX0DER) and 404 if I use IT marketplace (APJ6JRA9NG5V4)

**Comment by lucamancusodev** [comment]
solved the response errors! ✅
(was a cookie not setting problem)
now I got stock info of the SKU, tested with one available and one not.
the problem is that if I monitor one SKU that normally is not available, I still get "out of stock" while the others cookgroups don't.
